name: "Publish release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Publish release"
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "${{ github.ref_name }}"
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Build package
        run: poetry build
      - name: Publish package distributions to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish package distributions to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1