name: "Publish release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "${{ github.ref_name }}"